### PR TITLE
feat:community-banner

### PR DESCRIPTION
**Pull request by zleypner**
# Community Banner Component Implementation

## Description
Creating a new Community Banner component that will display community information in a standardized format.

## Component Requirements
- Community icon/shape display
- Community name text display
- "More info" interactive button
- Member count display

### Color Palette
- Primary Background: `#4ECCA3`
- Secondary Background: `#387478`
- Dark Text/Icon: `#232931`
- Accent: `#E36C59`
- Base Background: `#EEEEEE`

## Tasks
- [x] Create basic component structure
- [x] Implement responsive layout
- [x] Add icon/shape placeholder
- [x] Style component according to color palette
- [x] Add hover/interactive states for "More info" button
- [x] Add proper typings
- [ ] Write component tests
- [x] Add documentation
- [x] Add accessibility features

## Testing Checklist
- [ ] Component renders with all required props
- [ ] Button click handler works as expected
- [ ] Responsive behavior works on different screen sizes

## Screenshots
Pending

Related Issue: #15

Thank for reviewing my PR!

### CODE REVIEW

**Comment by zleypner** [comment]
> 🚧 **Work in Progress**: I am working on this issue and will update with implementation progress ASAP ⚡

**Comment by zleypner** [comment]
🚧 **Work in Progress**: Just updated the initial implementation! 

🎨 Still working on improving the design and polishing the UI

🔄 Will continue to update with more progress soon ⚡

**Comment by zleypner** [comment]
This is the current view for the banner: 
image

**Comment by evgongora** [comment]
> Hello there! I just uploaded an update. I would appretiate some feedback.
> 
> Would you like to move the sidebar under the banner? image

Right now we just need the component to be created, no need to be added in the layout, so you can go ahead and remove it for now. Thank you!

**Comment by evgongora** [comment]
After that we can go ahead and merge it.

**Comment by zleypner** [comment]
@evgongora Thank you I will! 
I will proceed with the updates asap!

**Review by evgongora — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
