### PR TITLE
feat: add highlighed vote component

### LINKED ISSUE #1: Create Highlighted votes component
Create the highlighted votes component which should have the Poll name (question), the category of the poll, and it should also include the amount of votes and comments that the poll has. The component should receive the following parameters: 
- question
- category
- votes
- comments 

Please refer to the color palette for the accurate hex code colors.

Component Image:
Screenshot 2024-12-12 at 01 08 28

Color Palette:
Color Palette

### PR DESCRIPTION
**Pull request by derianrddev**
# 📝 Add Highlighted Vote Component

## 🛠️ Issue
- Closes #1

## 📖 Description
- This PR introduces the Highlighted Vote component, which displays the poll's question, category, number of votes, and comments. This component was designed following the provided image and color palette.

## ✅ Changes made
- Implemented the `HighlightedVote` component.
- Utilized the Badge and Card components from shadcn/ui.
- The component accepts the following props:
  - `question`: The poll question (e.g., "What type of art is this?").
  - `category`: The category of the poll (e.g., "Painting").
  - `votes`: Number of votes the poll has received.
  - `comments`: Number of comments on the poll.
- Styled the component to match the provided design specifications and color palette.
- Integrated the component into the home page for testing and demonstration purposes.

## 🖼️ Media (screenshots/videos)
https://www.loom.com/share/e19f462135464017980e8bfb52c5728b?sid=1c1cd3c0-c4e6-47c5-bc54-435a4ed509f5

image

image

## 📜 Additional Notes
- Thank you very much for the issue.

### CODE REVIEW

**Review by evgongora — CHANGES_REQUESTED** [review]
Hey @derianrddev! Right now we just need the component to be created but not added to the layout of the website, could you please just leave the components for now :)

**Comment by derianrddev** [comment]
@evgongora ready!
image

**Comment by bitfalt** [comment]
LGTM! @derianrddev could you please solve the merge conflicts so that we merge your PR?

Thank you so much for your contribution :D

**Review by evgongora — APPROVED** [review]
LGTM!

**Pull request merged**
