### PR TITLE
feat: Added Navbar-item-component to "/components"

### LINKED ISSUE #8: Create Navbar Item component
Create the Navbar Item component which should have text. The component should receive the following parameters: text and the route (function) to where it should lead the user to once it is clicked. Please refer to the color palette for the accurate hex code colors.

Component Image:
Screenshot 2024-12-12 at 01 24 06

Color Palette:
Color Palette

### PR DESCRIPTION
**Pull request by Villarley**
Closes #8

# Tasks:

- [x] Implemented The component
- [X] Visual Tested
- [X] Tested route function
- [x] Included the types

---
# Description
Included the following code to implement the Navbar-Component-Item
```Typescript
import React from 'react';

interface NavbarItemProps {
  text: string;
  route: () => void;
}

const NavbarItem: React.FC<NavbarItemProps> = ({ text, route }) => {
  const handleClick = () => {
    if (route) {
      route();
    }
  };

  return (
    <button
      onClick={handleClick}
      className="bg-[#E36C59] text-white font-bold text-lg rounded-full px-6 py-2 shadow-lg hover:bg-[#D9564D] transition-all"
    >
      {text}
    </button>
  );
};

export default NavbarItem;

```

# Evidence
image

### CODE REVIEW

**Comment by Villarley** [comment]
Work In progress 🚧🚧🚧

**Comment by bitfalt** [comment]
hey @Villarley, good job so far. Could you please add a picture of how the component looks once you're finished.

Thank you for your contribution :D

**Comment by Villarley** [comment]
> hey @Villarley, good job so far. Could you please add a picture of how the component looks once you're finished.
> 
> Thank you for your contribution :D

Hey @bitfalt ready!

**Review by evgongora — APPROVED** [review]
LGTM! Thank you so much!

**Pull request merged**
