### PR TITLE
Create Characteristic - Landing Page component #13

### PR DESCRIPTION
**Pull request by Luluameh**
Landing Page created

### CODE REVIEW

**Review by evgongora — CHANGES_REQUESTED** [review]
Hey @Luluameh! Since we still don't have a PR template, could you please add a description of the changes you made, screenshots of the build and the look of the component.

**Comment by evgongora** [comment]
Also please resolve the conflicting files :)

**Comment by evgongora** [comment]
Any updates? @Luluameh

**Review by bitfalt — APPROVED** [review]
lgtm! Thank you for the contribution.

**Pull request merged**
